# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9wvFj-NB8lFb16b39uBcY1zoo7WhrBw

## Crime Data Analysis in Cities Using Python 🚔📊

---



---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Load the dataset
df = pd.read_csv("crime_dataset_india.csv")

#Display basic info and first few rows
df.info(), df.head()

#Convert date columns to datetime format
df["Date Reported"] = pd.to_datetime(df["Date Reported"], errors = "coerce")
df["Date of Occurrence"] = pd.to_datetime(df["Date of Occurrence"], errors = "coerce")
df["Date Case Closed"] = pd.to_datetime(df["Date Case Closed"], errors = "coerce")

#Handling missing values in "Date Case Closed"
df["Date Case Closed"].fillna("not closed", inplace=True)

#Standardizing categorical values(e.g., Gender, case closed status)
df["Victim Gender"] = df["Victim Gender"].str.upper()
df["Case Closed"] = df["Case Closed"].str.capitalize()

#Verify Changes
df.info(), df.head()

#set plot style
sns.set(style="darkgrid")

# 1. Crime Distribution by sity
plt.figure(figsize=(12,5))
top_cities = df["City"].value_counts().head(10)
sns.barplot(x=top_cities.index, y=top_cities.values, palette="viridis")
plt.xticks(rotation=45)
plt.xlabel("City")
plt.ylabel("Number of Crimes")
plt.title("Top 10 Cities with Highest Crime Rates")
plt.show()

plt.figure(figsize=(12,5))
top_crimes = df["Crime Description"].value_counts().head(10)
sns.barplot(x=top_crimes.values, y=top_crimes.index, palette="magma")
plt.xlabel("Number of Cases")
plt.ylabel("Crime Type")
plt.title("Top 10 Most Common Crimes")
plt.show()

df["Year"] = df["Date Reported"].dt.year  # Extract Year

plt.figure(figsize=(12, 5))
crime_trend = df["Year"].value_counts().sort_index()
sns.lineplot(x=crime_trend.index, y=crime_trend.values, marker="o", color="red")
plt.xlabel("Year")
plt.ylabel("Number of Crimes")
plt.title("Crime Trends Over the Years")
plt.show()

plt.figure(figsize=(12, 5))
top_weapons = df["Weapon Used"].value_counts().head(10)  # Top 10 weapons used
sns.barplot(x=top_weapons.values, y=top_weapons.index, palette="coolwarm")
plt.xlabel("Number of Cases")
plt.ylabel("Weapon Type")
plt.title("Top 10 Weapons Used in Crimes")
plt.show()

plt.figure(figsize=(8, 5))
case_status = df["Case Closed"].value_counts()
sns.barplot(x=case_status.index, y=case_status.values, palette="Set2")
plt.xlabel("Case Status")
plt.ylabel("Number of Cases")
plt.title("Case Closure Status")
plt.show()
